/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedClientRouteRouteImport } from './routes/_authenticated/client/route'
import { Route as AuthenticatedPlatformRouteRouteImport } from './routes/_authenticated/platform/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppCaisseRouteImport } from './routes/_authenticated/app/caisse'
import { Route as AuthenticatedAppReglagesRouteImport } from './routes/_authenticated/app/reglages'
import { Route as AuthenticatedAppSalleRouteImport } from './routes/_authenticated/app/salle'
import { Route as AuthenticatedAppStatsRouteImport } from './routes/_authenticated/app/stats'
import { Route as AuthenticatedAppTicketsRouteImport } from './routes/_authenticated/app/tickets'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client/index'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientRouteRoute =
  AuthenticatedClientRouteRouteImport.update({
    id: '/client',
    path: '/client',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformRouteRoute =
  AuthenticatedPlatformRouteRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppCaisseRoute = AuthenticatedAppCaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppReglagesRoute =
  AuthenticatedAppReglagesRouteImport.update({
    id: '/reglages',
    path: '/reglages',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSalleRoute = AuthenticatedAppSalleRouteImport.update({
  id: '/salle',
  path: '/salle',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppStatsRoute = AuthenticatedAppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppTicketsRoute = AuthenticatedAppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientRouteRoute,
  } as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlatformRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/client': typeof AuthenticatedClientRouteRouteWithChildren
  '/platform': typeof AuthenticatedPlatformRouteRouteWithChildren
  '/app/caisse': typeof AuthenticatedAppCaisseRoute
  '/app/reglages': typeof AuthenticatedAppReglagesRoute
  '/app/salle': typeof AuthenticatedAppSalleRoute
  '/app/stats': typeof AuthenticatedAppStatsRoute
  '/app/tickets': typeof AuthenticatedAppTicketsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/caisse': typeof AuthenticatedAppCaisseRoute
  '/app/reglages': typeof AuthenticatedAppReglagesRoute
  '/app/salle': typeof AuthenticatedAppSalleRoute
  '/app/stats': typeof AuthenticatedAppStatsRoute
  '/app/tickets': typeof AuthenticatedAppTicketsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/client': typeof AuthenticatedClientRouteRouteWithChildren
  '/_authenticated/platform': typeof AuthenticatedPlatformRouteRouteWithChildren
  '/_authenticated/app/caisse': typeof AuthenticatedAppCaisseRoute
  '/_authenticated/app/reglages': typeof AuthenticatedAppReglagesRoute
  '/_authenticated/app/salle': typeof AuthenticatedAppSalleRoute
  '/_authenticated/app/stats': typeof AuthenticatedAppStatsRoute
  '/_authenticated/app/tickets': typeof AuthenticatedAppTicketsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/client'
    | '/platform'
    | '/app/caisse'
    | '/app/reglages'
    | '/app/salle'
    | '/app/stats'
    | '/app/tickets'
    | '/app/'
    | '/client/'
    | '/platform/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/caisse'
    | '/app/reglages'
    | '/app/salle'
    | '/app/stats'
    | '/app/tickets'
    | '/app'
    | '/client'
    | '/platform'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/client'
    | '/_authenticated/platform'
    | '/_authenticated/app/caisse'
    | '/_authenticated/app/reglages'
    | '/_authenticated/app/salle'
    | '/_authenticated/app/stats'
    | '/_authenticated/app/tickets'
    | '/_authenticated/app/'
    | '/_authenticated/client/'
    | '/_authenticated/platform/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/caisse': {
      id: '/_authenticated/app/caisse'
      path: '/caisse'
      fullPath: '/app/caisse'
      preLoaderRoute: typeof AuthenticatedAppCaisseRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/reglages': {
      id: '/_authenticated/app/reglages'
      path: '/reglages'
      fullPath: '/app/reglages'
      preLoaderRoute: typeof AuthenticatedAppReglagesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/salle': {
      id: '/_authenticated/app/salle'
      path: '/salle'
      fullPath: '/app/salle'
      preLoaderRoute: typeof AuthenticatedAppSalleRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/stats': {
      id: '/_authenticated/app/stats'
      path: '/stats'
      fullPath: '/app/stats'
      preLoaderRoute: typeof AuthenticatedAppStatsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/tickets': {
      id: '/_authenticated/app/tickets'
      path: '/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AuthenticatedAppTicketsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedClientRouteRoute
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppCaisseRoute: typeof AuthenticatedAppCaisseRoute
  AuthenticatedAppReglagesRoute: typeof AuthenticatedAppReglagesRoute
  AuthenticatedAppSalleRoute: typeof AuthenticatedAppSalleRoute
  AuthenticatedAppStatsRoute: typeof AuthenticatedAppStatsRoute
  AuthenticatedAppTicketsRoute: typeof AuthenticatedAppTicketsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppCaisseRoute: AuthenticatedAppCaisseRoute,
  AuthenticatedAppReglagesRoute: AuthenticatedAppReglagesRoute,
  AuthenticatedAppSalleRoute: AuthenticatedAppSalleRoute,
  AuthenticatedAppStatsRoute: AuthenticatedAppStatsRoute,
  AuthenticatedAppTicketsRoute: AuthenticatedAppTicketsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedClientRouteRouteChildren {
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
}

const AuthenticatedClientRouteRouteChildren: AuthenticatedClientRouteRouteChildren =
  {
    AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
  }

const AuthenticatedClientRouteRouteWithChildren =
  AuthenticatedClientRouteRoute._addFileChildren(
    AuthenticatedClientRouteRouteChildren,
  )

interface AuthenticatedPlatformRouteRouteChildren {
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
}

const AuthenticatedPlatformRouteRouteChildren: AuthenticatedPlatformRouteRouteChildren =
  {
    AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
  }

const AuthenticatedPlatformRouteRouteWithChildren =
  AuthenticatedPlatformRouteRoute._addFileChildren(
    AuthenticatedPlatformRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedClientRouteRoute: typeof AuthenticatedClientRouteRouteWithChildren
  AuthenticatedPlatformRouteRoute: typeof AuthenticatedPlatformRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedClientRouteRoute: AuthenticatedClientRouteRouteWithChildren,
  AuthenticatedPlatformRouteRoute: AuthenticatedPlatformRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
